In [1]:
import tensorflow as tf

In [2]:
print(tf.add(2,3))
print(tf.add([1,2],[3,4]))
print(tf.square(5))
print(tf.reduce_sum([1,2,3]))

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


In [3]:
print(tf.square(2)+ tf.square(3))

tf.Tensor(13, shape=(), dtype=int32)


In [4]:
x = tf.matmul([[1]],[[2,3]])
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor([[2 3]], shape=(1, 2), dtype=int32)
(1, 2)
<dtype: 'int32'>


In [5]:
import numpy as np

ndarray = np.ones([3,3])
print("Tensorflow operations convert numpy arrays to tensors automatically")
tensor = tf.multiply(ndarray,42)
print(tensor)

print("...and NumPy operations convert Tensors to numpy arrays automatically")
print(np.add(tensor,1))

print("The .numpy() method explicitly converts a tensor to a numpy array")
print(tensor.numpy())

Tensorflow operations convert numpy arrays to tensors automatically
tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)
...and NumPy operations convert Tensors to numpy arrays automatically
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]
The .numpy() method explicitly converts a tensor to a numpy array
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


In [6]:
x = tf.random.uniform([3,3])

print("Is there a GPU available: ")
print(tf.config.experimental.list_physical_devices("GPU"))

print("Is the Tensor on GPU#0: ")
print(x.device.endswith('GPU:0'))

Is there a GPU available: 
[]
Is the Tensor on GPU#0: 
False


In [10]:
v = tf.Variable(1.0)
assert v.numpy() == 1.0

In [11]:
class Model(object):
    def __init__(self):
        self.W = tf.Variable(5.0)
        self.b = tf.Variable(0.0)
    def __call__(self, x):
        return self.W * x + self.b
model = Model()

assert model(3.0).numpy() == 15.0